services:

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: h18_fastapi:0.0.1
    container_name: fastapi_app
    ports:
      - 5001:5000
    environment:
      - DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TG_API_KEY=${TG_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    image: h18_bot:0.0.1
    container_name: telegram_bot
    environment:
      - DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}
      - TG_API_KEY=${TG_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: pg_database
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: